version: '3.1'

services:

  mysql:
    image: mysql
    ports:
        - "6033:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: you-shall-not-pass
        MYSQL_USER: zuzka
        MYSQL_PASSWORD: you-shall-not-pass-neither
        MYSQL_DATABASE: eshop