version: '3.1'

services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
        - "6033:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: you-shall-not-pass
        MYSQL_DATABASE: eshop

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./../swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/openapi.yaml